#!/usr/bin/env bash
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#

dotnet restore src/Api.Claims/ && \
    dotnet build src/Api.Claims/ && \
    echo "Now, run the following to start the project: dotnet run -p src/Api.Claims/Api.Claims.csproj --launch-profile web"
