version: '3.8'
services:
  api:
    build: .
    ports:
      - "80:5000"  # Map host port 80 to container port 5000
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Set environment for API
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: adesfontaines
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: claims
    ports:
      - "5432:5432"  # Expose the PostgreSQL port (optional for local development)
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adesfontaines -d claims"]
      interval: 10s
      timeout: 5s
      retries: 3
  prometheus:
    image: prom/prometheus:latest  # Use the latest Prometheus image
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml # Mount your Prometheus config
    ports:
      - "9090:9090"  # Expose Prometheus on port 9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml' 
    depends_on:
      - api
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3001:3000"   
    depends_on:
      - prometheus
    volumes:
      -prometheus:/prometheus

volumes:
  pgdata:
  database:
  prometheus: