name: Build and deploy container to Azure

env:
  AZURE_WEBAPP_NAME: api-claims   # set this to your application's name

on:
  push:
    branches: 
      - main 
      - release/*  # Added this line

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Test with Coverage
      run: dotnet test tests/api.tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput='./Cobertura.xml'--no-build --verbosity normal

    - name: Check Coverage Threshold
      if: ${{ always() }}  # Always run, even if previous steps fail
      run: |
        threshold=0
        actual=$(grep "<coverage line-rate="Cobertura.xml | sed -E 's/.*line-rate="([0-9.]+)".*/\1/' | awk '{ sum += $1 } END { if (NR > 0) print sum / NR * 100; else print 0 }')
        if (( $(echo "$actual < $threshold" | bc -l) )); then
          echo "Code coverage ($actual%) is below the threshold ($threshold%). Failing the build."
          exit 1
        fi
        echo "Code coverage ($actual%) meets the threshold."
  package_and_deploy:
    name: Package and Deploy
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - name: Set up Docker Compose
      uses: docker/setup-compose-v2@v2
    - name: Build and run services
      run: docker compose up -d --build